main: me.PSK1103.GUIMarketplaceDirectory.GUIMarketplaceDirectory
name: GUIMarketplaceDirectory
author: PSK1103
api-version: "1.14"
version: 1.0.0
description: gui marketplace directory

commands:

  GUIMD:
    description: Searching for shops/items and approving/removing shops
    aliases: [gmd,guimd]
    usage: do /gmd help for all use cases

permissions:
  GUIMD.moderate:
    default: op
    description: Allows moderation of shops